
train:
  rescale: 255
  image_size: (224,224)
  batch_size: 10
  include_top: false
  input_shape: (224,224,3)
  loss: 'categorical_crossentropy'
  metrics: 
    - accuracy
  learning_rate: 0.01
  momentum: 0.9
  nbr_epoch: 1
  mlflow_server_url:  "http://ec2-54-160-246-226.compute-1.amazonaws.com:8080/" 
  experiment_name: "testing"